### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by luxorina** [Bucknell-Biol364/Biology207tutorial#3]
https://github.com/Bucknell-Biol364/Biology207tutorial/blob/1b62d4b25f73bdf4e07f11b79529d4a0791aa4ff/Biology%20207%20tutorial.Rmd#L1
@KateBille @jkoss6 @mwm021 

This is ready to be peer reviewed. I would suggest looking at the whole GitHub for this, and starting with the readme file. Thank you!

**Comment by jkoss6** [comment]
1) Line 13 to 19 use this code chunk instead: if (!require("ggplot2")) install.packages("ggplot2"); library(ggplot2). It doesn't report errors because it checks to see if you already have it installed and installs it if you don't, but does nothing if its already installed and loaded into your library.

**Comment by KateBille** [comment]
Hey guys, this looks great!

I really like the video you made for them to follow along.

For a new user it may be confusing to just tell them to download and open an rmd file in R though. I think it would be helpful to tell them to clone/download your repository and open documents from there rather than open them through git.

Another option would be to make an Archive folder in your repository to hide all of the documents that they will not need to use. That way it will be clear which files you want them to open

**Comment by mwm021** [comment]
@KateBille @jkoss6 Thanks for your suggestions! We fixed our Rmd file and redid the part of the video that has the if (!......) code in it. The Rmd and Md files have all of our updated material in them.
